version: '3.8'
services:
  dust3r-demo:
    build:
      context: .. 
    ports:
      - "8080:8080"
    environment:
      - DEVICE=cuda
      - MODEL=${MODEL:-DUSt3R_ViTLarge_BaseDecoder_512_dpt.pth}
    cap_add:
      - IPC_LOCK
      - SYS_RESOURCE
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
